# Generated by Django 3.1.5 on 2021-03-02 14:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_auto_20210302_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
