# Generated by Django 3.1.5 on 2021-01-14 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_title', models.CharField(max_length=250)),
                ('app_logo_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AppDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.appindex')),
            ],
        ),
    ]
