# Generated by Django 3.1.5 on 2021-01-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppDetails',
            new_name='AppDetail',
        ),
    ]
