# Generated by Django 3.1.5 on 2021-01-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210119_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetail',
            name='app_desc',
            field=models.CharField(default='example', max_length=500),
        ),
    ]
