# Generated by Django 3.1.5 on 2021-01-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210119_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetail',
            name='app_desc',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
