# Generated by Django 3.1.5 on 2021-01-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20210119_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetail',
            name='app_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.appindex'),
        ),
    ]
